theme = "dark_plus"

[editor]
line-number = "relative"
mouse = true
auto-save = true
cursorline = true
cursorcolumn = true
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

### https://docs.helix-editor.com/master/configuration.html#editorwhitespace-section
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
###


[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "separator", "version-control", "separator"]
right = ["position", "position-percentage", "total-line-numbers"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
